version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - dbdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: web
    environment:
      - DB_UNAME=postgres
      - DB_PASS=postgres
      - GMAIL_UNAME=insert_your_email
      - GMAIL_PASS=insert_your_password
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Rails-Docker
    ports:
      - "3000:3000"
        
volumes:
  dbdata: